-- 신규 멤버 온보딩 제출 (2026-09-29) — /welcome/ 페이지가 쓰고, 운영진 탭 '설정'에서 '명단에 추가'로 팀빌더에 올린다.
create table if not exists public.member_onboard (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null,
  eng_name    text,
  gender      text check (gender in ('남','여')),
  phone       text not null,
  jersey      int,
  position    text,
  note        text,
  status      text not null default 'pending' check (status in ('pending','done'))
);
alter table public.member_onboard enable row level security;
-- 누구나 제출(insert)·운영진 페이지가 익명 키로 읽기(select)·처리 표시(update status) — join_requests 와 같은 수준
create policy onboard_insert on public.member_onboard for insert to anon, authenticated with check (true);
create policy onboard_select on public.member_onboard for select to anon, authenticated using (true);
create policy onboard_update on public.member_onboard for update to anon, authenticated using (true) with check (true);
